package ir.ac.kntu.userlevel;

public enum Roles {
    TOURADD,
    TOURREMOVEOREDIT,
    TOURLEADERADD,
    TOURLEADERREMOVEOREDIT,
    AREAADD,
    AREAREMOVEOREDIT,
    TOURINFORMATIONADD,
    TOURINFORMATIONREMOVEOREDIT,
    EMPLOYEEADD,
    EMPLOYEEREMOVEOREDIT,
    CUSTOMERADD,
    CUSTOMERREMOVEOREDIT,
    ADMINEDIT,
}
